
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: node-app-redis
    ports:
      - 6379:6379
    networks:
      - node-app-network

  postgres:
    image: postgres:16
    container_name: node-app-postgres
    restart: always
    mem_limit: 1g
    cpu_count: 1
    mem_reservation: 512m
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks: 
      - node-app-network

  mongo:
    image: mongo:8
    container_name: node-app-mongo
    restart: always
    mem_limit: 1g
    cpu_count: 1
    mem_reservation: 512m
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    networks:
      - node-app-network

networks:
  node-app-network:
    driver: bridge
